# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
pod 'Firebase/Core'

target 'reSEEt' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for reSEEt

  target 'reSEEtTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'reSEEtUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
